"""Constants for the Novafos integration."""

from __future__ import annotations
from typing import Final

# Get Sensor classification and unit definitions:
from homeassistant.components.sensor import SensorStateClass
from homeassistant.components.sensor import SensorDeviceClass
from homeassistant.const import UnitOfEnergy
from homeassistant.const import UnitOfVolume

from .model import NovafosSensorDescription

DOMAIN = "novafos"

# KMD can publish hourly readings several days late. Re-import a rolling window
# on every refresh so delayed readings replace the temporary zero-consumption
# statistics already generated by Home Assistant.
STATISTICS_LOOKBACK_DAYS = 31

# Entries migrated from versions that only fetched one day are reconciled once
# from KMD's earliest available timestamp.
HISTORY_RECONCILIATION_KEY = "reconcile_full_history"

# A rolling refresh compares Home Assistant's year-to-date sum with KMD's own
# yearly total and falls back to a full reconciliation when they disagree by
# more than this.  The allowance covers today's hours, which are part of the
# yearly total but not yet imported as hourly statistics.
RECONCILIATION_TOLERANCE_ABS = 0.5
RECONCILIATION_TOLERANCE_REL = 0.02

# Default name for sensor prefix texts (possibly other things)
DEFAULT_NAME = "Novafos"

WATER_SENSOR_TYPES: Final[tuple[NovafosSensorDescription, ...]] = (
    NovafosSensorDescription(
        sensor_type="water",
        key="hourly",
        name="Water hourly consumption",
        entity_registry_enabled_default=True,
        native_unit_of_measurement=UnitOfVolume.CUBIC_METERS,
        suggested_display_precision=3,
        # Home Assistant only permits total/total_increasing state classes for
        # the water device class. This entity is an interval measurement, not a
        # cumulative meter, so leave the device class unset.
        device_class=None,
        icon="mdi:water",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    NovafosSensorDescription(
        sensor_type="water",
        key="statistics",
        name="Water statistics",
        entity_registry_enabled_default=True,
        native_unit_of_measurement=UnitOfVolume.CUBIC_METERS,
        suggested_display_precision=3,
        device_class=SensorDeviceClass.WATER,
        icon="mdi:water",
        state_class=SensorStateClass.TOTAL,
    ),
)

EXTRA_WATER_SENSOR_TYPES: Final[tuple[NovafosSensorDescription, ...]] = (
    NovafosSensorDescription(
        sensor_type="water",
        key="statistics_day",
        name="Water statistics day",
        entity_registry_enabled_default=True,
        native_unit_of_measurement=UnitOfVolume.CUBIC_METERS,
        suggested_display_precision=3,
        device_class=SensorDeviceClass.WATER,
        icon="mdi:water",
        state_class=SensorStateClass.TOTAL,
    ),
    NovafosSensorDescription(
        sensor_type="water",
        key="statistics_week",
        name="Water statistics week",
        entity_registry_enabled_default=True,
        native_unit_of_measurement=UnitOfVolume.CUBIC_METERS,
        suggested_display_precision=3,
        device_class=SensorDeviceClass.WATER,
        icon="mdi:water",
        state_class=SensorStateClass.TOTAL,
    ),
    NovafosSensorDescription(
        sensor_type="water",
        key="statistics_month",
        name="Water statistics month",
        entity_registry_enabled_default=True,
        native_unit_of_measurement=UnitOfVolume.CUBIC_METERS,
        suggested_display_precision=3,
        device_class=SensorDeviceClass.WATER,
        icon="mdi:water",
        state_class=SensorStateClass.TOTAL,
    ),
    NovafosSensorDescription(
        sensor_type="water",
        key="statistic_years",
        name="Water statistics year",
        entity_registry_enabled_default=True,
        native_unit_of_measurement=UnitOfVolume.CUBIC_METERS,
        suggested_display_precision=3,
        device_class=SensorDeviceClass.WATER,
        icon="mdi:water",
        state_class=SensorStateClass.TOTAL,
    ),
)

HEATING_SENSOR_TYPES: Final[tuple[NovafosSensorDescription, ...]] = (
    NovafosSensorDescription(
        sensor_type="heating",
        key="hourly",
        name="Heating hourly consumption",
        entity_registry_enabled_default=True,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        suggested_display_precision=3,
        # This is an interval measurement rather than a cumulative energy meter.
        device_class=None,
        icon="mdi:lightning-bolt-circle",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    NovafosSensorDescription(
        sensor_type="heating",
        key="statistics",
        name="Heating statistics",
        entity_registry_enabled_default=True,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        suggested_display_precision=3,
        device_class=SensorDeviceClass.ENERGY,
        icon="mdi:lightning-bolt-circle",
        state_class=SensorStateClass.TOTAL,
    ),
)

EXTRA_HEATING_SENSOR_TYPES: Final[tuple[NovafosSensorDescription, ...]] = (
    NovafosSensorDescription(
        sensor_type="heating",
        key="statistics_day",
        name="Heating statistics day",
        entity_registry_enabled_default=True,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        suggested_display_precision=3,
        device_class=SensorDeviceClass.ENERGY,
        icon="mdi:lightning-bolt-circle",
        state_class=SensorStateClass.TOTAL,
    ),
    NovafosSensorDescription(
        sensor_type="heating",
        key="statistics_week",
        name="Heating statistics week",
        entity_registry_enabled_default=True,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        suggested_display_precision=3,
        device_class=SensorDeviceClass.ENERGY,
        icon="mdi:lightning-bolt-circle",
        state_class=SensorStateClass.TOTAL,
    ),
    NovafosSensorDescription(
        sensor_type="heating",
        key="statistics_month",
        name="Heating statistics month",
        entity_registry_enabled_default=True,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        suggested_display_precision=3,
        device_class=SensorDeviceClass.ENERGY,
        icon="mdi:lightning-bolt-circle",
        state_class=SensorStateClass.TOTAL,
    ),
    NovafosSensorDescription(
        sensor_type="heating",
        key="statistic_years",
        name="Heating statistics year",
        entity_registry_enabled_default=True,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        suggested_display_precision=3,
        device_class=SensorDeviceClass.ENERGY,
        icon="mdi:lightning-bolt-circle",
        state_class=SensorStateClass.TOTAL,
    ),
)
