"""Constants for the Novafos integration."""

from __future__ import annotations
from typing import Final

# Get Sensor classification and unit definitions:
from homeassistant.components.sensor import SensorStateClass
from homeassistant.components.sensor import SensorDeviceClass
from homeassistant.const import UnitOfEnergy
from homeassistant.const import UnitOfVolume

from .model import NovafosSensorDescription

DOMAIN = "novafos"

# KMD can publish hourly readings several days late. Re-import a rolling window
# on every refresh so delayed readings replace the temporary zero-consumption
# statistics already generated by Home Assistant.
STATISTICS_LOOKBACK_DAYS = 31

# Entries migrated from versions that only fetched one day are reconciled once
# from KMD's earliest available timestamp.
HISTORY_RECONCILIATION_KEY = "reconcile_full_history"

# A rolling refresh compares Home Assistant's year-to-date sum with KMD's own
# yearly total and falls back to a full reconciliation when they disagree by
# more than this.  The allowance covers today's hours, which are part of the
# yearly total but not yet imported as hourly statistics.
RECONCILIATION_TOLERANCE_ABS = 0.5
RECONCILIATION_TOLERANCE_REL = 0.02

# KMD reports each meter's unit.  District heating is billed in kWh, MWh, GJ
# or m³ of hot water depending on the utility, so it cannot be assumed.
# Unit name -> (Home Assistant unit, recorder unit class, energy device class?)
_KMD_UNITS: Final = {
    "m³": (UnitOfVolume.CUBIC_METERS, "volume", False),
    "m3": (UnitOfVolume.CUBIC_METERS, "volume", False),
    "kwh": (UnitOfEnergy.KILO_WATT_HOUR, "energy", True),
    "mwh": (UnitOfEnergy.MEGA_WATT_HOUR, "energy", True),
    "gj": (UnitOfEnergy.GIGA_JOULE, "energy", True),
}


def meter_unit(meter_device: dict) -> tuple[str, str, SensorDeviceClass | None]:
    """Return (unit, unit class, device class) for a KMD meter."""
    name = str((meter_device.get("Unit") or {}).get("Name", "")).strip()
    unit, unit_class, is_energy = _KMD_UNITS.get(name.lower(), (None, None, None))
    if meter_device.get("type") == "water":
        return UnitOfVolume.CUBIC_METERS, "volume", SensorDeviceClass.WATER
    if unit is None:
        # Unknown or missing unit: keep the historical default.
        return UnitOfEnergy.KILO_WATT_HOUR, "energy", SensorDeviceClass.ENERGY
    if is_energy:
        return unit, unit_class, SensorDeviceClass.ENERGY
    # Heating measured as a volume of hot water.
    return unit, unit_class, SensorDeviceClass.VOLUME


# Optional static price per unit (for example DKK per m³), per meter type.
# The options dialog edits the current year's price; prices are kept per year
# so a new price never reprices hours from earlier years.  0 disables it.
def price_option(meter_type: str) -> str:
    """Return the options key of the price field in the options dialog."""
    return f"{meter_type}_price"


def prices_option(meter_type: str) -> str:
    """Return the options key holding the {year: price} mapping."""
    return f"{meter_type}_prices"


# Default name for sensor prefix texts (possibly other things)
DEFAULT_NAME = "Novafos"

WATER_SENSOR_TYPES: Final[tuple[NovafosSensorDescription, ...]] = (
    NovafosSensorDescription(
        sensor_type="water",
        key="hourly",
        name="Water hourly consumption",
        entity_registry_enabled_default=True,
        native_unit_of_measurement=UnitOfVolume.CUBIC_METERS,
        suggested_display_precision=3,
        # Home Assistant only permits total/total_increasing state classes for
        # the water device class. This entity is an interval measurement, not a
        # cumulative meter, so leave the device class unset.
        device_class=None,
        icon="mdi:water",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    NovafosSensorDescription(
        sensor_type="water",
        key="statistics",
        name="Water statistics",
        entity_registry_enabled_default=True,
        native_unit_of_measurement=UnitOfVolume.CUBIC_METERS,
        suggested_display_precision=3,
        device_class=SensorDeviceClass.WATER,
        icon="mdi:water",
        state_class=SensorStateClass.TOTAL,
    ),
)

EXTRA_WATER_SENSOR_TYPES: Final[tuple[NovafosSensorDescription, ...]] = (
    NovafosSensorDescription(
        sensor_type="water",
        key="statistics_day",
        name="Water statistics day",
        entity_registry_enabled_default=True,
        native_unit_of_measurement=UnitOfVolume.CUBIC_METERS,
        suggested_display_precision=3,
        device_class=SensorDeviceClass.WATER,
        icon="mdi:water",
        state_class=SensorStateClass.TOTAL,
    ),
    NovafosSensorDescription(
        sensor_type="water",
        key="statistics_week",
        name="Water statistics week",
        entity_registry_enabled_default=True,
        native_unit_of_measurement=UnitOfVolume.CUBIC_METERS,
        suggested_display_precision=3,
        device_class=SensorDeviceClass.WATER,
        icon="mdi:water",
        state_class=SensorStateClass.TOTAL,
    ),
    NovafosSensorDescription(
        sensor_type="water",
        key="statistics_month",
        name="Water statistics month",
        entity_registry_enabled_default=True,
        native_unit_of_measurement=UnitOfVolume.CUBIC_METERS,
        suggested_display_precision=3,
        device_class=SensorDeviceClass.WATER,
        icon="mdi:water",
        state_class=SensorStateClass.TOTAL,
    ),
    NovafosSensorDescription(
        sensor_type="water",
        key="statistic_years",
        name="Water statistics year",
        entity_registry_enabled_default=True,
        native_unit_of_measurement=UnitOfVolume.CUBIC_METERS,
        suggested_display_precision=3,
        device_class=SensorDeviceClass.WATER,
        icon="mdi:water",
        state_class=SensorStateClass.TOTAL,
    ),
)

HEATING_SENSOR_TYPES: Final[tuple[NovafosSensorDescription, ...]] = (
    NovafosSensorDescription(
        sensor_type="heating",
        key="hourly",
        name="Heating hourly consumption",
        entity_registry_enabled_default=True,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        suggested_display_precision=3,
        # This is an interval measurement rather than a cumulative energy meter.
        device_class=None,
        icon="mdi:lightning-bolt-circle",
        state_class=SensorStateClass.MEASUREMENT,
    ),
    NovafosSensorDescription(
        sensor_type="heating",
        key="statistics",
        name="Heating statistics",
        entity_registry_enabled_default=True,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        suggested_display_precision=3,
        device_class=SensorDeviceClass.ENERGY,
        icon="mdi:lightning-bolt-circle",
        state_class=SensorStateClass.TOTAL,
    ),
)

EXTRA_HEATING_SENSOR_TYPES: Final[tuple[NovafosSensorDescription, ...]] = (
    NovafosSensorDescription(
        sensor_type="heating",
        key="statistics_day",
        name="Heating statistics day",
        entity_registry_enabled_default=True,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        suggested_display_precision=3,
        device_class=SensorDeviceClass.ENERGY,
        icon="mdi:lightning-bolt-circle",
        state_class=SensorStateClass.TOTAL,
    ),
    NovafosSensorDescription(
        sensor_type="heating",
        key="statistics_week",
        name="Heating statistics week",
        entity_registry_enabled_default=True,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        suggested_display_precision=3,
        device_class=SensorDeviceClass.ENERGY,
        icon="mdi:lightning-bolt-circle",
        state_class=SensorStateClass.TOTAL,
    ),
    NovafosSensorDescription(
        sensor_type="heating",
        key="statistics_month",
        name="Heating statistics month",
        entity_registry_enabled_default=True,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        suggested_display_precision=3,
        device_class=SensorDeviceClass.ENERGY,
        icon="mdi:lightning-bolt-circle",
        state_class=SensorStateClass.TOTAL,
    ),
    NovafosSensorDescription(
        sensor_type="heating",
        key="statistic_years",
        name="Heating statistics year",
        entity_registry_enabled_default=True,
        native_unit_of_measurement=UnitOfEnergy.KILO_WATT_HOUR,
        suggested_display_precision=3,
        device_class=SensorDeviceClass.ENERGY,
        icon="mdi:lightning-bolt-circle",
        state_class=SensorStateClass.TOTAL,
    ),
)
